language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t Tonyzaa11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Tonyzaa11/docker-react npm run test
