sudo: required
services:
  - docker

before_install:
  - docker build -t tonyzaa11/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tonyzaa11/docker-react npm run test
  deploy:
    provider: elasticbeanstalk   #any provider :aws,Digital ocean,azure, etc..
    region: "ap-southeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-780608562012"
    bucket_path: "docker-react" # same as th app name
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"


      
  
